image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  stage: build
  image: docker:stable-dind
  before_script:
    - docker info
    - docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PWD}
  script:
    - docker build -t ${DOCKERHUB_LOGIN}/otus-reddit${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA} ./reddit
    - docker push ${DOCKERHUB_LOGIN}/otus-reddit${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker images

variables:
  DATABASE_URL: 'mongo:27017'

before_script:
  - cd reddit
  - bundle install

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
