comment:
  image:
    repository: allien/comment
    tag: "1.0"
  service:
    externalPort: 9292

post:
  image:
    repository: allien/post
    tag: "1.0"
  service:
    externalPort: 5000

ui:
  image:
    repository: allien/ui
    tag: "1.0"
  service:
    externalPort: 9292

mongodb:
  auth:
    enabled: "false"
