---
- name: Deploy App
  hosts: docker
  become: true
  tags: deploy

  tasks:
    - debug:
        var: image_to_run

    - name: Pull docker image
      docker_image:
        name: "{{ image_to_run }}"
        source: pull
        state: present

    - name: Create docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_to_run }}"
        detach: yes
        state: started
        published_ports:
          - 80:9292
