apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pd-storage
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhmvntcsngdu2kt68vhv
