Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dockerhost" do |machine|
    machine.vm.box = "ubuntu/xenial64"
    machine.vm.hostname = "dockerhost"
    machine.vm.network :private_network, ip: "10.10.10.20"

    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
       "docker" => ["dockerhost"],
       "docker:vars" => {"image_to_run" => "allien/otus-reddit:1.0",
                         "container_name" => "reddit-app"
                        }
      }
    end
  end
end
